"""empty message

Revision ID: c7ac31b2cacc
Revises: 
Create Date: 2022-11-17 11:31:41.143712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ac31b2cacc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estagiario_origem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estagiario_origem')
    # ### end Alembic commands ###
